# Site settings
title: Diogo Mónica's Website
email: diogo.monica@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Diogo Mónica is the security lead at Docker, an open platform for building, shipping and running distributed applications. He was an early employee at Square where he led the platform security team. He received his BSc, MSc and PhD degrees in Computer Science and is currently a Security Researcher at the Technical University of Lisbon. Diogo also serves on the board of advisors of several security startups and is a long-time IEEE Volunteer.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty
url: "https://diogomonica.com" # the base hostname & protocol for your site
twitter_username: diogomonica
github_username:  diogomonica
paginate: 5
paginate_path: "/archives/page/:num"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap

sass:
    style: compressed