

# Site Settings
title: 						"Diogo Monica"
email: 						"diogo.monica@gmail.com@gmail.com"
description: 					"I lead Security @Docker, advise a handful of Startups and do Security Research. Follow @diogomonica on twitter or learn a little bit more about me."
baseurl: 					""
url: 						"/"
logourl: 					"/assets/img/diogo_monica_14_cropped_small.png"
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Diogo Monica"
author_url: 				"https://diogomonica.com"
author_bio: 					"I lead Security @Docker, advise a handful of Startups and do Security Research. Follow @diogomonica on twitter or learn a little bit more about me."
author_email: 				"diogomonica@gmail.com"
author_image: 				"/assets/img/diogo_monica_14_cropped_small.png"


# Social Settings
twitter_url: 				"https://twitter.com/diogomonica"
facebook_url: 				"https://facebook.com/diogomonica"
github_url:  				"https://github.com/diogomonica"
# youtube_url:  				"http://youtube.com"
# dribbble_url:  				"http://dribbble.com"
# googleplus_url: 			"http://google.com/plus"
# instagram_url:  			"http://instagram.com/"
# pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"https://www.linkedin.com/in/diogomonica"


# Theme Settings
theme_disqus_shortname: 	""
theme_google_comments: 		false
theme_analytics_id: 		""
theme_analytics_domain: 	""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

